In [1]:
import pandas

# pandas.options.display.max_columns = None
# pandas.options.display.max_rows = None

csv_data = pandas.read_csv("imdb_top_1000.csv")
csv_data

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

In [29]:
# Question 1: How many movies have a perfect IMDB metascore (100)?
perfect_meta_score = csv_data[csv_data['Meta_score'] == 100.0]
perfect_meta_score

# Answer: 12

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
50,https://m.media-amazon.com/images/M/MV5BY2IzZG...,Casablanca,1942,U,102 min,"Drama, Romance, War",8.5,A cynical expatriate American cafe owner strug...,100.0,Michael Curtiz,Humphrey Bogart,Ingrid Bergman,Paul Henreid,Claude Rains,522093,"1,024,560"
81,https://m.media-amazon.com/images/M/MV5BNGUxYW...,Rear Window,1954,U,112 min,"Mystery, Thriller",8.4,A wheelchair-bound photographer spies on his n...,100.0,Alfred Hitchcock,James Stewart,Grace Kelly,Wendell Corey,Thelma Ritter,444074,"36,764,313"
116,https://m.media-amazon.com/images/M/MV5BYWY5Zj...,Lawrence of Arabia,1962,U,228 min,"Adventure, Biography, Drama",8.3,"The story of T.E. Lawrence, the English office...",100.0,David Lean,Peter O'Toole,Alec Guinness,Anthony Quinn,Jack Hawkins,268085,"44,824,144"
119,https://m.media-amazon.com/images/M/MV5BYTE4OD...,Vertigo,1958,A,128 min,"Mystery, Romance, Thriller",8.3,A former police detective juggles wrestling wi...,100.0,Alfred Hitchcock,James Stewart,Kim Novak,Barbara Bel Geddes,Tom Helmore,364368,"3,200,000"
124,https://m.media-amazon.com/images/M/MV5BYjBiOT...,Citizen Kane,1941,UA,119 min,"Drama, Mystery",8.3,Following the death of publishing tycoon Charl...,100.0,Orson Welles,Orson Welles,Joseph Cotten,Dorothy Comingore,Agnes Moorehead,403351,"1,585,634"
260,https://m.media-amazon.com/images/M/MV5BYTg1Mm...,Trois couleurs: Rouge,1994,U,99 min,"Drama, Mystery, Romance",8.1,A model discovers a retired judge is keen on i...,100.0,Krzysztof Kieslowski,IrÃ¨ne Jacob,Jean-Louis Trintignant,FrÃ©dÃ©rique Feder,Jean-Pierre Lorit,90729,"4,043,686"
274,https://m.media-amazon.com/images/M/MV5BZmQzMD...,Fanny och Alexander,1982,A,188 min,Drama,8.1,Two young Swedish children experience the many...,100.0,Ingmar Bergman,Bertil Guve,Pernilla Allwin,Kristina Adolphson,BÃ¶rje Ahlstedt,57784,"4,971,340"
423,https://m.media-amazon.com/images/M/MV5BODFlYz...,Il conformista,1970,UA,113 min,Drama,8.0,A weak-willed Italian man becomes a fascist fl...,100.0,Bernardo Bertolucci,Jean-Louis Trintignant,Stefania Sandrelli,Gastone Moschin,Enzo Tarascio,27067,"541,940"
440,https://m.media-amazon.com/images/M/MV5BMjE5NT...,Sweet Smell of Success,1957,Approved,96 min,"Drama, Film-Noir",8.0,Powerful but unethical Broadway columnist J.J....,100.0,Alexander Mackendrick,Burt Lancaster,Tony Curtis,Susan Harrison,Martin Milner,28137,NaN
491,https://m.media-amazon.com/images/M/MV5BMTYzND...,Boyhood,2014,A,165 min,Drama,7.9,"The life of Mason, from early childhood to his...",100.0,Richard Linklater,Ellar Coltrane,Patricia Arquette,Ethan Hawke,Elijah Smith,335533,"25,379,975"
559,https://m.media-amazon.com/images/M/MV5BYTc1NG...,Notorious,1946,U,102 min,"Drama, Film-Noir, Romance",7.9,A woman is asked to spy on a group of Nazi fri...,100.0,Alfred Hitchcock,Cary Grant,Ingrid Bergman,Claude Rains,Louis Calhern,92306,"10,464,000"

In [3]:
# Question 2: How many movies have a perfect IMDB rating? (10)
perfect_IMDB_rating = csv_data[csv_data['IMDB_Rating'] == 10.0]
perfect_IMDB_rating
# Answer: None

Empty DataFrame
Columns: [Poster_Link, Series_Title, Released_Year, Certificate, Runtime, Genre, IMDB_Rating, Overview, Meta_score, Director, Star1, Star2, Star3, Star4, No_of_Votes, Gross]
Index: []

In [23]:
#  Question 3: Which director has received the highest average IMDB rating from their movies?
poor_directrate = csv_data.groupby('Director')['IMDB_Rating'].mean()
poor_directrate

# Answer: Aamir Khan

Director
Aamir Khan             8.40
Aaron Sorkin           7.80
Abdellatif Kechiche    7.70
Abhishek Chaubey       7.80
Abhishek Kapoor        7.70
                       ...
Zack Snyder            7.60
Zaza Urushadze         8.20
Zoya Akhtar            8.05
Ã‡agan Irmak            8.30
Ã–mer Faruk Sorak       8.00
Name: IMDB_Rating, Length: 548, dtype: float64

In [43]:
# Question 4: Which actor appeared in the most movies with the average metascore ranking of >90?
meta_actor = { [[csv_data.groupby('Star1')['Meta_score'].mean]], 
              [[csv_data.groupby('Star2')['Meta_score'].mean]], 
              [[csv_data.groupby('Star3')['Meta_score'].mean]],
             [[csv_data.groupby('Star4')['Meta_score'].mean]]}
                                 
meta_actor

TypeError: unhashable type: 'list'

In [34]:
# Question 5: How many actors have an average of >90 for their metascore across the movies they've been in?
actor_average = {[csv_data]
    
}

TypeError: unhashable type: 'list'

In [44]:
# Question 6: What is the highest grossing movie from this list?
highest_gross = csv_data.max("Gross")
col = "Gross"
highest_gross = csv_data.loc[csv_data[col].idxmax()]
highest_gross

ValueError: No axis named Gross for object type DataFrame

In [35]:
# Question 7: Which celebrities appeared in multiple movies with the same director?

In [36]:
# Question 8: hich combination of actors received a high gross for their movie?

In [37]:
# Question 9: Which actor has the highest total gross amount for all the movies they starred in?

In [38]:
# Question 10: Which director achieved the highest gross amount for all the movies they directed?